# Generated by Django 4.0.4 on 2022-06-01 18:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10000)])),
                ('unread', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['user', '-created'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user'], name='messages_user_id_d457bc_idx'),
        ),
    ]
