# Use postgres/example user/password credentials
version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
    ports:
      - "5432:5432"
    volumes:
      - postgress-data:/var/lib/postgresql/data:rw
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD:-admin}
    volumes:
      - pgadmin-data:/var/lib/pgadmin4
    ports:
      - "5050:80"

volumes:
  postgress-data:
  pgadmin-data:
