# Generated by Django 4.0.4 on 2022-05-29 09:39

import django.core.validators
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(40)])),
                ('tag', models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(5)])),
                ('leagues', models.ManyToManyField(related_name='teams', to='events.teamleague')),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='teams_name_12b53a_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_team_name'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('tag'), name='unique_lower_team_tag'),
        ),
    ]
