# Generated by Django 4.0.4 on 2022-05-30 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
        ('events', '0004_alter_singleapplication_driver_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leagues',
        ),
        migrations.CreateModel(
            name='TeamParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivers', models.ManyToManyField(related_name='team_driver_participations', to='drivers.driver')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_participations', to='events.league')),
                ('reserve_drivers', models.ManyToManyField(related_name='team_reserve_driver_participations', to='drivers.driver')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='teams.team')),
            ],
            options={
                'db_table': 'team_participations',
            },
        ),
    ]
