# Generated by Django 4.0.4 on 2022-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('agitator', 'Agitator'), ('brusso', 'Brusso'), ('osprey', 'Osprey'), ('mantra', 'Mantra'), ('piccino', 'Piccino'), ('bonk', 'Bonk'), ('storm', 'Storm'), ('panther', 'Panther'), ('conquest', 'Conquest'), ('vost', 'Vost'), ('impact', 'Impact'), ('feather', 'Feather'), ('road_rebel', 'Road_rebel'), ('loose_cannon', 'Loose_cannon')], default='road_rebel', max_length=20, unique=True)),
                ('car_class', models.CharField(choices=[('super_truck', 'Super Truck'), ('50s_gt', '50s GT'), ('60s_gp', '60s GP'), ('80s_gp', '80s GP'), ('piccino_cup', 'Piccino Cup'), ('eurotruck', 'Eurotruck'), ('gp', 'GP'), ('gt', 'GT'), ('prototype', 'Prototpye'), ('rally', 'Rally'), ('stock_car', 'Stock Car'), ('superlights', 'Superlights'), ('touring_car', 'Touring Car'), ('muscle_car', 'Muscle Car')], default='touring_car', max_length=30)),
                ('main_type', models.CharField(choices=[('street', 'Street'), ('rallycross', 'Rallycross')], default='street', max_length=20)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('whistle_valley', 'Whistle Valley'), ('sugar_hill', 'Sugar Hill'), ('maple_ridge', 'Maple Ridge'), ('magdalena', 'Magdalena'), ('copperwood', 'Copperwood'), ('rennvoort', 'Rennvoort'), ('interstate', 'Interstate'), ('buffalo_hill', 'Buffalo Hill'), ('lost_lagoons', 'Lost Lagoons'), ('bullseye_speedway', 'Bullseye Speedway'), ('faenza', 'Faenza'), ('siena', 'Siena'), ('speedopolis', 'Speedopolis'), ('thunder_point', 'Thunder Point'), ('tilksport', 'Tilksport')], default='thunder_point_gp', max_length=100, unique=True)),
                ('layout', models.CharField(choices=[('gp', 'GP'), ('club', 'Club'), ('mini', 'Mini'), ('oval', 'Oval'), ('rallycross', 'Rallycross')], max_length=20)),
                ('reversed', models.BooleanField(default=False)),
                ('has_dirt', models.BooleanField(default=False)),
                ('length_meters', models.FloatField()),
            ],
            options={
                'db_table': 'tracks',
                'ordering': ['name', 'layout'],
            },
        ),
    ]
