# Generated by Django 4.0.4 on 2022-05-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
        ('content', '0001_initial'),
        ('events', '0002_application_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaceResults',
            new_name='RaceResult',
        ),
    ]
