# Generated by Django 4.0.4 on 2022-05-30 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
        ('teams', '0001_initial'),
        ('events', '0003_rename_raceresults_raceresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleapplication',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_driver_applications', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='teamapplication',
            name='drivers',
            field=models.ManyToManyField(related_name='team_driver_applications', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='teamapplication',
            name='reserve_drivers',
            field=models.ManyToManyField(related_name='team_reserve_driver_applications', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='teamapplication',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='teams.team'),
        ),
        migrations.AlterModelTable(
            name='application',
            table='applications',
        ),
        migrations.AlterModelTable(
            name='singleapplication',
            table='single_applications',
        ),
        migrations.AlterModelTable(
            name='teamapplication',
            table='team_applications',
        ),
    ]
