# Generated by Django 4.0.4 on 2022-06-01 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_singleapplication_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penalty',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raceresult',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='singleleague',
            name='points_calculation_type',
            field=models.CharField(choices=[('all', 'Points of every race count'), ('cut_worst', 'Do not use worst single/team result'), ('cut_two_worst', 'Do not use the two worst single/team results'), ('total_time', 'Use the total time of all races to determine the standings.')], default='all', max_length=30),
        ),
        migrations.AlterField(
            model_name='teamleague',
            name='points_calculation_type',
            field=models.CharField(choices=[('all', 'Points of every race count'), ('cut_worst', 'Do not use worst team result'), ('cut_two_worst', 'Do not use the two worst team results'), ('total_time', 'Use the total time of all races to determine the standings.')], default='all', max_length=30),
        ),
    ]
